mbta/alerts_concierge

apps/alert_processor/test/alert_processor/service_info/service_info_cache_test.exs

We have a task in the queue to address the various test failures caused by live data changing, and in the meantime this frequently blocks other tasks for no good reason.

fix: temporarily skip spurious test failure

---

apps/alert_processor/lib/service_info/service_info_cache.ex
apps/alert_processor/test/alert_processor/service_info/service_info_cache_test.exs
apps/alert_processor/test/integration/matching_test.exs
apps/concierge_site/lib/views/route_helper.ex
apps/concierge_site/lib/views/stop_select_helper.ex
apps/concierge_site/test/lib/schedule_test.exs
apps/concierge_site/test/web/views/trip_card_helper_test.exs
apps/concierge_site/test/web/views/trip_review_card_helper_test.exs

If a user had any subscriptions involving a route that didn't exist anymore, the subscriptions page would crash on render, preventing any further managing of subscriptions. This also blocked the test suite from passing, as the recently eliminated bus route 57A was used in a few test cases.
This fixes the immediate issue by displaying "Unknown Route" as the route name. For now attempting to edit such a subscription will still cause a crash, but it can be deleted, and will otherwise not cause any harm.

Fix test failures and subscriptions page crash

---

apps/alert_processor/lib/rules_engine/informed_entity_filter.ex
apps/alert_processor/lib/service_info/service_info_cache.ex
apps/alert_processor/test/alert_processor/rules_engine/informed_entity_filter_test.exs
apps/alert_processor/test/alert_processor/service_info/service_info_cache_test.exs

In c4914b5 we removed a seemingly unused clause of `get_route` that allowed passing `nil` as the route ID. Though this was not covered by any tests, it turned out to be used when an uncommon set of conditions occurred, and this caused processing of the "oldest" group of alerts to always crash in production.
This adds two tests that both fail in the presence of this bug: one for `ServiceInfoCache` that explicitly tests passing `nil` as the route ID, and one for `InformedEntityFilter` replicating the conditions that cause `nil` to be passed as the route ID.
This also fixes an incorrect pattern in `InformedEntityFilter` that never would have matched, because it was matching a subscription `type` (which only has atom values) against a string.

fix: alert processing crash in `get_route`

---

apps/alert_processor/test/alert_processor/lock_test.exs

Noticed this failure for the first time in the CI run for #1152, so it's pretty rare, but possible.
`Process.exit` is not synchronous, and this test did not wait for the process to exit before continuing, so occasionally it would fail because the lock was not released by the time the test tried to acquire it.

test: fix rare failure in `Lock` test

---

.github/workflows/deploy.yml

`workflow_dispatch` workflows need to exist in some form on the repo's main branch to be available, so this adds a "deploy" workflow that does nothing, to enable testing of the real deploy workflow on a branch.

ci: add no-op deploy workflow

---

.github/workflows/deploy.yml

See [successful dev-green deploy](https://github.com/mbta/alerts_concierge/runs/2898382424?check_suite_focus=true) from this branch!
Some notable "innovations" I'd like to backport or at least socialize:
* This allows manually deploying to any environment, and auto-deploying the main branch to `dev`, using a common workflow. The UI isn't great in that you have to [type in the name of the environment](https://user-images.githubusercontent.com/394835/123157928-2857d000-d439-11eb-8df5-8ce5b2ed76d0.png) instead of selecting it from a list — but if you typo, nothing terrible happens (it does pollute the list of "Environments" in the repo settings).
* The auto-deploy only happens after CI finishes, and only if it passed... at least, it _should_ work this way, but it doesn't appear there's any …

ci: enable deployment with Actions

---

.github/workflows/ci.yml
apps/alert_processor/test/alert_processor/api/api_client_test.exs
apps/alert_processor/test/integration/matching_test.exs

`github.ref` here is a branch or tag name (not a commit hash), so this means if we push new commits to a branch that already has an ongoing CI job, it will be cancelled in favor of the new one.

ci: add cancel-in-progress concurrency option

---

apps/concierge_site/lib/controllers/account_controller.ex
apps/concierge_site/lib/mailchimp.ex
apps/concierge_site/lib/mailchimp/mailchimp_fake_client.ex
apps/concierge_site/test/lib/mailchimp_test.exs

This was a request from the team drafting new MBTA privacy policies. Currently when a user self-service deletes their account, we permanently delete all data connected to them _except_ their membership on the weekly digest in Mailchimp, where we only mark them as unsubscribed. It will simplify the privacy policy (and also better reflect the intent of the action) if deleting your account truly deletes everything, including Mailchimp data.
This change is deployed to dev-green, where I tested that existing functionality still works and that the new delete request goes through.

Delete Mailchimp data when account is deleted

---

apps/concierge_site/assets/css/_header.scss
apps/concierge_site/assets/css/_landing_page.scss
apps/concierge_site/lib/templates/layout/app.html.eex

This was previously used to display a warning about the govDelivery version of T-Alerts being turned off. It is not referenced anywhere in the code since September 2018.

refactor: remove unused "header note" feature

---

.github/workflows/ci.yml
.tool-versions
Dockerfile
apps/concierge_site/assets/js/app.js
apps/concierge_site/assets/js/touch-support.js
apps/concierge_site/assets/package-lock.json
apps/concierge_site/lib/templates/error/403.html.eex
apps/concierge_site/lib/templates/error/404.html.eex
apps/concierge_site/lib/templates/error/500.html.eex
apps/concierge_site/lib/templates/layout/app.html.eex

Thankfully it seems like there are no incompatibilities here other than the Yarn stuff I saw before (and addressed in #1167), so this wasn't much more than increasing a version number. The `package-lock` changes are due to the new version of NPM generating the file differently, but should not have changed any actual installed packages.

build: upgrade to latest Node LTS release

---

.github/workflows/ci.yml
apps/concierge_site/lib/controllers/account_controller.ex
apps/concierge_site/lib/controllers/trip_controller.ex
apps/concierge_site/lib/templates/account/edit.html.eex
apps/concierge_site/lib/templates/account/options_new.html.eex
apps/concierge_site/lib/templates/trip/index.html.eex
apps/concierge_site/lib/views/account_view.ex
apps/concierge_site/test/web/controllers/account_controller_test.exs
apps/concierge_site/test/web/controllers/trip_controller_test.exs

Currently a `none` communication mode is displayed the same as `email`, making it appear email delivery is enabled when in fact it isn't. There's no other indication in the UI that alerts are disabled, or explanation as to why, except when the reason is SMS opt-out and the user is still inside the opt-out freeze period.
With these changes, if a user's communication mode is `none`:
* their Settings page correctly has neither of the delivery options selected
* a flash appears on their Settings page explaining how this happened and what they can do to resolve it (for all circumstances, not just when inside the SMS freeze period)
* a flash appears on their Subscriptions page, which is the "home page" when signed in, explaining that alerts are disabled and to access the Settings page to …

Improve UI and explanations when alerts are disabled

---

Dockerfile

* Use pre-built `hexpm/elixir` image instead of starting from an Erlang image and manually installing Elixir
* Use `node` image to build assets instead of installing Node in the Elixir image (allows specifying exact version)
* Upgrade to current stable Debian release ("Bullseye")
* Use `slim` Debian images to omit unneeded packages where possible
* Use `dumb-init` as entrypoint to ensure signals are handled correctly
Overall, these improvements reduce our deploy time by about 2 minutes, and better align with how we're currently doing Docker builds on other projects like Dotcom and Arrow.

build: Dockerfile improvements

---

apps/alert_processor/test/integration/matching_test.exs
apps/concierge_site/assets/static/analytics.txt
apps/concierge_site/assets/static/robots.txt
apps/concierge_site/lib/endpoint.ex

This occurred because the `<link rel="icon">` in the HTML used the "digested" filename in production, but following this link would give a 404, since the site was only configured to serve the un-digested `favicon.ico`. Depending on whether the browser "preferred" the `<link>` or the file at `/favicon.ico`, it sometimes wouldn't show the icon.
Using `only_matching` instead of `only` in `Plug.Static` allows serving digested files at the root, since strings specified here only need to be a prefix of the first path component instead of matching it exactly.

Fix missing favicon

---

.github/workflows/ci.yml
README.md
apps/alert_processor/priv/repo/structure.sql
apps/alert_processor/test/alert_processor/rules_engine/text_replacement_test.exs
apps/alert_processor/test/alert_processor/service_info/service_info_cache_test.exs
apps/concierge_site/test/lib/schedule_test.exs

All deployed environments other than `prod` have already been upgraded without incident, and `prod` will likely be upgraded this week. ✨

chore: upgrade to Postgres 13

---

.github/workflows/ci.yml

Since these tools are "global" and part of the Elixir install, they should be reinstalled if we have a new language version, not if we have a new version of the project dependencies.
See: https://github.com/mbta/.github/pull/11

ci: install Rebar and Hex on ASDF cache miss

---

apps/alert_processor/lib/model/query.ex
apps/concierge_site/test/lib/schedule_test.exs

Temporarily deployed to production to ensure this is reasonably optimized — the query completes in less than a second.

feat(admin): report for subscription count by stop

---

apps/alert_processor/lib/model/query.ex
apps/concierge_site/test/lib/schedule_test.exs

This adds a column `subscribed_users` which is the count of users who have any subscriptions, regardless of paused status.

feat(admin): add column to users report

---

apps/alert_processor/mix.exs
apps/concierge_site/mix.exs

It's unclear whether this still worked, and in any case we don't use it for anything.

build: remove "app version" generation

---

apps/alert_processor/mix.exs
apps/concierge_site/mix.exs

Almost none of these were necessary for our current versions of Elixir and dependencies.

refactor: clean up `extra_applications`

---

mix.exs

Since CI always runs in `MIX_ENV=test` and Sobelow was only listed as a `dev` dependency, it failed with a "task could not be found" error. Unclear how the change that added Sobelow passed CI in the first place before being merged.

fix: Sobelow was not accessible to CI

---

apps/concierge_site/lib/guardian/auth_error_handler.ex

Sentry report: https://sentry.io/organizations/mbtace/issues/2930926732/?environment=prod&project=5583106
Guardian 0.14.x had a default set of error handlers it would fall back to if you didn't handle a particular type of error. This is no longer the case in Guardian 1.x due to the error handler API changing to use different clauses of a single callback, instead of multiple callbacks. This means we need to include a fallback clause ourselves.

fix: 500 error when auth token expired

---

apps/alert_processor/lib/model/query.ex
apps/concierge_site/test/web/controllers/admin/queries_controller_test.exs
apps/concierge_site/test/web/controllers/session_controller_test.exs

Following a vulnerability scan that created a massive number of fake accounts, complete with fake subscriptions, the numbers in our reports were a bit skewed. We can compensate for this by ignoring accounts where alerts are disabled, which happens when either their email address bounces (which we saw with these accounts, since they made up non-existent addresses) or they opt out via SMS. In cases where this occurs "naturally", it should still be okay to not include those accounts in the reports, since we are primarily interested in subscription stats for users where those subscriptions are actually generating notifications.

feat(admin): filter inactive users out of reports

---

apps/alert_processor/test/alert_processor/model/subscription_test.exs
apps/concierge_site/lib/controllers/account_controller.ex

When automated spam-bots try to create an account without even loading the JavaScript for the reCAPTCHA, the required parameter is missing and we get a crash report because no clause matches in the controller. This can also happen legitimately if the user's browser is old enough to not be supported by reCAPTCHA or is blocking JavaScript, so we can provide a nice error message.

fix: add fallback clause for account create

---

apps/alert_processor/test/alert_processor/dissemination/mass_notifier_test.exs
apps/alert_processor/test/alert_processor/reminders/processor/processor_test.exs

The queue is a global resource, so tests that use it cannot be `async`. We also need to make sure we `reset` it before such tests.

test: fix intermittent `SendingQueue` failures

---

apps/concierge_site/assets/js/select-stop-choices.js

Changes to attribute ordering due to the Phoenix upgrade in fe6c785c introduced a bug where route icons in stop selectors would display in the opposite of the intended order (see below). Since the reversed ordering is a consequence of using `float: right`, we can un-reverse it in the same place we apply this style.

fix: reversed route icon order in stop selectors

---

.github/workflows/ci.yml

This installs dependencies exactly as specified in the lockfile, and always exits with an error in cases where `npm install` would update `package.json` and/or the lockfile (e.g. if the lockfile did not match the version constraints in `package.json`). Also, it's faster. ⚡️
Previously we didn't use this because our NodeJS version was too old for the included version of NPM to support this command.
Ref: https://docs.npmjs.com/cli/v6/commands/npm-ci
**Note:** [Tested](https://github.com/mbta/alerts_concierge/runs/6083937006?check_suite_focus=true) by temporarily commenting out the cache-hit condition on this step, since otherwise it would have been skipped.

ci: use `npm ci` instead of `npm install`

---

.github/workflows/deploy.yml

This allows selecting an environment from those defined on the repo, instead of having to type in an environment name. Reference: https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/

ci: use `environment` input in deploy workflow

---

apps/concierge_site/lib/controllers/email_opened_controller.ex
apps/concierge_site/lib/helpers/mail_helper.ex
apps/concierge_site/lib/router.ex
apps/concierge_site/test/lib/dissemination/notification_email_test.exs
apps/concierge_site/test/lib/helpers/mail_helper_test.exs
apps/concierge_site/test/web/controllers/email_opened_controller_test.exs

Forgot to consider that the endpoint could potentially be hit without the query params set 🥲 
currently this just swallows the request, but do we want to log anything in this case? I think maybe this could have been originally caused by email clients scrubbing out query parameters on images 🤔 could be an interesting stat to track

fix: add overload to catch missing query params

---

apps/alert_processor/lib/dissemination/notification_sender.ex
apps/alert_processor/test/alert_processor/dissemination/notification_sender_test.exs
apps/alert_processor/test/support/mocks/mailer_mock.ex

Following some clean up work done recently, all of our emails should be "valid" now (in the sense that the should at least be well-formed, not necessarily real).
Once this merges in, I'll keep my eye on Sentry for any new errors that pop up

chore: clean up unnecessary email handling code

---

apps/alert_processor/lib/alert_parsing/alert_parser.ex
apps/alert_processor/lib/dissemination/notification_sender.ex
apps/alert_processor/lib/model/alert.ex

We want to track some operational performance metrics in Splunk. One thing that we want to track is the total time taken to send all notifications for an alert. However, since alerts can persist over longer periods of time, tracking just the `alert_id` is insufficient. Thus, with this PR we want to add a concept of a `batch_id`. This will allow us to see how long it takes for us to send all notifications for an alert _in a given batch_ rather than over the entire lifetime of the alert.

chore: track notification batches

---

apps/alert_processor/lib/dissemination/notification_sender.ex
apps/alert_processor/test/alert_processor/dissemination/notification_sender_test.exs
apps/concierge_site/test/lib/schedule_test.exs

This is required to comply with SMS regulations. See https://app.asana.com/0/1113179098808463/1202332063233179/f for more context

Add "T-Alerts - " prefix to all SMS messages

---

.github/workflows/deploy-a.yml

As a part of migrating this infrastructure into Terraform, we're creating new clusters that don't have the `-a` suffix. This updates the main deploy step to deploy to the non `-a` clusters, but keeps around a deploy step to use them if we need it.

fix: deploy to regular (non-`-a`) clusters

---

README.md
apps/alert_processor/test/integration/matching_test.exs
apps/concierge_site/test/lib/schedule_test.exs

No ticket, some of the tests are just tied to schedule data so need to be updated periodically when the rating changes and they fail. (Side note, there's a [ticket](https://app.asana.com/0/1167196461144361/1199513856779936) in the backlog to improve this situation).
- docs: Update the chromedriver installation command
- fix(test): Remove schedule-specific test conditions
These conditions would break when the schedule changed, and don't add
anything meaningful to the tests.
- fix(test): Update test data to use current schedule
Background: These tests use a set of specific trip IDs. At the time the
tests are run, the trip for the current day of the week must have
schedules present in the API.
[Passing test run](https://github.com/mbta/alerts_concierge/actions/runs/3431182352)

fix(test): Update tests to work with the current schedule

---

.tool-versions
Dockerfile

No ticket
- erlang from 24.3.4.5 to 24.3.4.6
- elixir from 1.13.3 to 1.13.4
[Successful build and deploy](https://github.com/mbta/alerts_concierge/actions/runs/3464596137/jobs/5786307545)

deps: Update patch-level versions of Erlang & Elixir

---

.github/dependabot.yml

Asana ticket: [Configure Dependabot to keep dependencies up-to-date automatically](https://app.asana.com/0/1167196461144361/1203413849690490)
Maintain both mix and npm dependencies. Follow the version upgrade rules in the respective lockfiles.

deps: Configure Dependabot to keep dependencies up-to-date

---

.tool-versions
Dockerfile
apps/concierge_site/assets/package-lock.json

No ticket
Also sneaking in:
fix: Update phoenix version in lockfile
[Successful build and deploy](https://github.com/mbta/alerts_concierge/actions/runs/3525266952/jobs/5911771651)

deps: Update node to the latest LTS version 18.12.1

---

apps/alert_processor/lib/model/subscription.ex
apps/alert_processor/test/alert_processor/model/subscription_test.exs

No ticket, came across this orphan code while working in the file.

refactor: Delete unused `pause_count` function

---

apps/concierge_site/assets/package-lock.json
apps/concierge_site/assets/package.json

No ticket.
None of these contained any breaking changes that affected us.
- deps: Update babel-loader from 8.3.0 to 9.1.0
- deps: Update copy-webpack-plugin from 9.1.0 to 11.0.0
- deps: Update css-minimizer-webpack-plugin from 3.4.1 to 4.2.2
- deps: Update sass-loader from 12.6.0 to 13.2.0
- deps: Update webpack-cli from 4.9.0 to 5.0.0

deps: Update npm dependencies across major versions

---

apps/alert_processor/lib/model/subscription.ex

Allow the pieces to use indexes. The old query had to run a sequential scan.
Even if the cumulative time doesn't decrease drastically, hopefully individual queries will be much shorter than the timeout we are currently sometimes seeing.
Before:
```
explain SELECT s0."id", s0."user_id", s0."trip_id", s0."relevant_days", s0."start_time", s0."end_time", s0."travel_start_time", s0."travel_end_time", s0."origin", s0."destination", s0."type", s0."route", s0."route_type", s0."direction_id", s0."origin_lat", s0."origin_long", s0."destination_lat", s0."destination_long", s0."rank", s0."return_trip", s0."facility_types", s0."paused", s0."parent_id", s0."is_admin", s0."inserted_at", s0."updated_at" FROM "subscriptions" AS s0 WHERE ( ( ( ( ( s0."is_admin" = true ) OR s0."route_type" = ANY ( '{0, 1, …
```

fix: Break apart database query with many ors

---

scripts/db_dump_sanitize.sh

Asana ticket: [Set up reusable pipeline](https://app.asana.com/0/1167196461144361/1203573682044259)
This script makes it easier to run the existing sanitize script we had, and codifies dumping the DB and writing to S3. This is intended to be run in the `app-alerts-concierge-etl` instance, introduced in https://github.com/mbta/devops/pull/754.

feat: Script to dump the DB, sanitize, and upload to S3

---

apps/concierge_site/assets/package-lock.json

- build(deps-dev): bump @babel/core from 7.20.5 to 7.20.12 in /apps/concierge_site/assets https://github.com/mbta/alerts_concierge/pull/1274
- build(deps-dev): bump babel-loader from 9.1.0 to 9.1.2 in /apps/concierge_site/assets https://github.com/mbta/alerts_concierge/pull/1273

build(deps-dev): babel-related updates

---

apps/concierge_site/assets/package-lock.json

- build(deps-dev): bump css-loader from 6.7.2 to 6.7.3 in /apps/concierge_site/assets #1266 
- build(deps): bump jquery from 3.6.1 to 3.6.3 in /apps/concierge_site/assets #1269
- build(deps): bump core-js from 3.26.1 to 3.27.2 in /apps/concierge_site/assets #1277
- build(deps-dev): bump sass from 1.56.1 to 1.58.0 in /apps/concierge_site/assets #1280

build(deps): Collected npm updates

---

apps/alert_processor/priv/repo/migrations/20170601111510_add_uuid_extension.exs
apps/alert_processor/priv/repo/migrations/20170711152200_add_password_resets_table.exs
apps/alert_processor/priv/repo/migrations/20180220221033_trips.exs
apps/alert_processor/priv/repo/migrations/20200430210043_add_user_id_index_to_notifications.exs
apps/alert_processor/priv/repo/migrations/20230208195021_drop_uuid_ossp_extension.exs
apps/alert_processor/priv/repo/structure.sql
apps/concierge_site/test/web/controllers/trip_controller_test.exs

Part of getting [Set up a production-like environment to support load testing](https://app.asana.com/0/1167196461144361/1203535165046759) working.
The `gen_random_uuid` function is provided by Postgres starting in
version 13.
Remove the uuid-ossp extension that is no longer needed.
Also:
fix: Disable migration lock on concurrent migration
This was raised as necessary in the logs while running a migration.

feat: Use the built-in UUI generate function

---

apps/alert_processor/test/alert_processor/service_info/service_info_cache_test.exs

No Asana task, fixes a test that started failing today.
Reverts part of the test expectation changes from https://github.com/mbta/alerts_concierge/pull/1295 now that our GTFS file has been updated.

fix (test): Restore ferry stops to expected data

---

.github/workflows/create-asana-attachment.yaml

No Asana ticket, ironically.
I've already set the `ASANA_SECRET` repository secret.

ci: Create pull request attachments on Asana tasks

---

apps/concierge_site/config/config.exs
apps/concierge_site/lib/controllers/trip_controller.ex
apps/concierge_site/lib/templates/layout/app.html.eex
apps/concierge_site/lib/templates/page/account_deleted.html.eex
apps/concierge_site/lib/templates/trip/index.html.eex
apps/concierge_site/lib/views/helpers.ex
apps/concierge_site/lib/views/trip_view.ex
apps/concierge_site/test/web/views/trip_view_test.exs
config/runtime.exs

Asana ticket: [Add inline survey when riders delete account or all subscriptions](https://app.asana.com/0/1167196461144361/1204501447170890/f)
Show an Informizely survey if
- they actually delete their account
- they delete all of their subscriptions
Populate Informizely site and survey IDs from env vars since they need to be different values in dev vs. production.

feat: Survey a user who looks like they are deleting their account

---

apps/alert_processor/test/alert_processor/service_info/service_info_cache_test.exs

These tests were breaking but not in a way that was meaningful.

fix (test): Tweak expected results based on latest GTFS data

---

apps/concierge_site/lib/controllers/auth_controller.ex
apps/concierge_site/lib/helpers/session_helper.ex
apps/concierge_site/lib/router.ex
apps/concierge_site/lib/templates/account/edit_keycloak.html.eex
apps/concierge_site/test/web/controllers/auth_controller_test.exs

Asana ticket: [Update T-Alerts Logout Configuration](https://app.asana.com/0/1204819229687089/1204927567478482)
This logout URL is the new structure for Keycloak version 19.
fix: Retrieve the auth session before logging out
The user is actually logged in for this session action, so we want to
retrieve the auth credentials so that we can properly log the user out.
@ErinLMoore Note: this is just merging into the open branch for https://github.com/mbta/alerts_concierge/pull/1309, but I thought it would be useful to get a quick check from you anyway.

feat: Store the ID token and use it to log the user out

---

apps/alert_processor/lib/model/query.ex
apps/alert_processor/test/alert_processor/service_info/service_info_cache_test.exs

Query to list number of users who have at least one unpaused subscription that have child subscriptions.

New parents subscriptions query

---

apps/concierge_site/assets/js/radio-toggle.js
apps/concierge_site/lib/templates/account/edit_keycloak.html.eex

Asana ticket: [MBTA account links disappear when "Text me" is selected](https://app.asana.com/0/1204819229687089/1205257335187901/f)
Note that this is merging into the `mss-keycloak` branch.
Available for testing on [dev](https://alerts-concierge-dev.mbtace.com/account/edit).

fix: Always show "Your MBTA Account" in settings

---

apps/alert_processor/lib/alert_parsing/alert_parser.ex
apps/alert_processor/lib/model/alert.ex
apps/alert_processor/lib/model/notification.ex
apps/alert_processor/lib/rules_engine/notification_builder.ex
apps/alert_processor/priv/repo/migrations/20230830193726_add_images_to_alerts_and_notifications.exs
apps/alert_processor/priv/repo/structure.sql
apps/alert_processor/test/alert_processor/alert_parsing/alert_parser_test.exs
apps/alert_processor/test/alert_processor/rules_engine/notification_builder_test.exs
apps/concierge_site/assets/mjml/notification.mjml
apps/concierge_site/lib/mail_templates/notification.txt.eex
apps/concierge_site/test/integration/sending_test.exs
apps/concierge_site/test/lib/dissemination/notification_email_test.exs

Reference for the shape the image data comes in as: https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#message-translatedimage
Asana ticket:  https://app.asana.com/0/1167196461144361/1204624899415315/f

Adds image and alt text to emails

---

apps/alert_processor/test/alert_processor/service_info/service_info_cache_test.exs

No Asana ticket, I just noticed the failing test.
This must have been added in the latest GTFS release.

fix (test): Add a new stop to the test expectation

---

apps/alert_processor/test/integration/matching_test.exs

No ticket. This fixes tests that are [currently failing in CI](https://github.com/mbta/alerts_concierge/actions/runs/6511645499/job/17687900913?pr=1363) after the latest GTFS release.
[Successful CI run](https://github.com/mbta/alerts_concierge/actions/runs/6534640916/job/17742298536)

fix (test): Update trip IDs for latest GTFS

---

.github/workflows/deploy.yml

This PR migrates the deploy workflow to use v2 of `build-push-ecr` and `deploy-ecs` actions. 
There's a test failure happening in this pipeline, so I'd like to get team opinion here. I wouldn't have expected these changes to affect any test coverage.

Fix: Migrate GitHub actions to v2 and assumed role

---

apps/alert_processor/test/alert_processor/service_info/service_info_cache_test.exs

No Asana ticket—this fixes tests that are currently breaking.
This matches the current data we are receiving.

fix (test): Remove all Winthrop and East Boston Ferry stops

---

apps/alert_processor/lib/service_info/service_info_cache.ex

There are no running trips, and the app isn't properly handling a response with no data. That should be fixed properly, but in the meantime, this stops the bleeding.

HOT FIX: Don't fetch ferry data temporarily

---

apps/alert_processor/lib/model/notification.ex
apps/alert_processor/test/alert_processor/model/notification_test.exs
apps/concierge_site/assets/mjml/notification.mjml

Asana ticket: [Clarify where image links to in alt text](https://app.asana.com/0/1204819229687089/1206700151817918)

feat: Clarify where email image links to in alt text

---

apps/concierge_site/lib/helpers/session_helper.ex

Asana ticket: [T-Alerts auth cleanup](https://app.asana.com/0/1204819229687089/1206753793118218)

fix: Remove unused claims argument on sign_in

---

apps/alert_processor/test/integration/matching_test.exs

[Asana ticket](https://app.asana.com/0/1204819229687089/1207423324340490/f)
The commuter rail schedules changed recently, making some integration tests fail. This updates the tests with some valid trip IDs and their start times.

Updates commuter rail subscription for new schedule

---

apps/alert_processor/lib/model/query.ex

[Asana Ticket](https://app.asana.com/0/1204819229687089/1207463067725489/f)
This is a query that can be run from the admin panel. It was running quite slow but it turns only we only really need this data from the beginning of the previous month. This changes the start date of the query to be that.

Monthly New Users query update

---

apps/alert_processor/lib/model/user.ex
apps/alert_processor/test/alert_processor/model/user_test.exs
apps/concierge_site/lib/controllers/auth_controller.ex
apps/concierge_site/test/web/controllers/auth_controller_test.exs

[Asana ticket](https://app.asana.com/0/1204819229687089/1207565926717083/f)
Lets a user login in from keycloak if their user id matches either the `sub` id or the `mbta_uuid`. Does not log in and redirects to landing page if both are somehow found.

Login in with mbta_uuid

---

apps/alert_processor/test/alert_processor/service_info/service_info_cache_test.exs
apps/concierge_site/lib/router.ex

[ticket](https://app.asana.com/0/1204819229687089/1208252819442811/f)
A recent security audit revealed we need to add some more secure headers. The `put secure browser headers` plug takes care of most of them, so we were really only missing 2.

Add secure headers

---

apps/alert_processor/lib/dissemination/notification_sender.ex
apps/alert_processor/lib/model/notification.ex
apps/alert_processor/lib/rules_engine/notification_builder.ex
apps/alert_processor/priv/repo/migrations/20250523171312_add_notification_call_to_action.exs
apps/alert_processor/priv/repo/structure.sql
apps/alert_processor/test/alert_processor/dissemination/notification_sender_test.exs
apps/alert_processor/test/alert_processor/rules_engine/notification_builder_test.exs
apps/alert_processor/test/alert_processor/service_info/service_info_cache_test.exs
apps/alert_processor/test/integration/matching_test.exs
apps/concierge_site/assets/mjml/notification.mjml

Add a new line of text at the end of any bus delay alerts, letting users know they can check dotcom or the app for realtime information.
This adds a new column to the notifications table in the DB to keep a record of which CTA was included in their notification.
We include an `https://` scheme in the URL so that email clients render them as links, but remove them in texts, to save characters and because text clients don't usually require the scheme to render it as a link.
⚠️  This also shouldn't be merged before the /route redirects are deployed to dotcom prod and the MBTA Go URL is finalized, we'll be switching it to a deep link that directly opens the app, likely go.mbta.com
Added a few new unit tests to check the added behavior for notifications and SMS formatting, but I couldn't find …

feat: Add MBTA Go call to action for bus delay alerts

---

apps/alert_processor/lib/model/notification.ex
apps/alert_processor/test/alert_processor/rules_engine/notification_builder_test.exs
apps/alert_processor/test/integration/matching_test.exs

The new URL adds campaign tracking to the link so that we can tell when people are installing the app through this link.
This change should not be released until after https://github.com/mbta/mobile_app_backend/pull/363 is deployed to prod.

feat: Update MBTA Go CTA URL
