mbta/alerts_concierge

.github/workflows/ci.yml, .github/workflows/deploy.yml
See commit messages for details!
=> Rename master branch to main

apps/alert_processor/test/alert_processor/service_info/service_info_cache_test.exs, apps/concierge_site/assets/js/trip-form.js, apps/concierge_site/lib/plugs/rate_limit.ex, apps/concierge_site/test/lib/plugs/rate_limit_test.exs
Couple of other small commits which have their own explanations, but the original point of this was an investigation of a JS error I noticed. It turned out to be harmless, but is also fixed now, since doing so was trivial.
=> fix: JS error in subscription creation

apps/alert_processor/lib/lock.ex
This was originally implemented this way simply because `Repo.checkout` didn't exist in Ecto 2, and the idea was that we could simplify things by using a session-level lock after upgrading to Ecto 3. However, after further investigation, this is actually still the best way to do it. The comment now explains the rationale.
This also removes a `key >= 0` guard clause that was unnecessary, since lock keys can be any integer, including negative integers.
=> docs: explain `Lock` approach in light of Ecto 3

README.md, apps/alert_processor/priv/repo/structure.sql
I had to set up this repo afresh because my old laptop died, and noticed some improvements that could be made to the README. @zovt let me know if this lines up with your experience, or if I'm missing anything! (notably, I ran into an API rate-limiting issue like you did, which I figure makes it common enough to mention)
=> Improve setup instructions in README

apps/alert_processor/lib/model/query.ex
One thing I wasn't 100% sure about: the Asana ticket mentions:
> Should ignore bad emails and any other type of user created by bots, vulnerability scanners, etc.
I checked `email_rejection_status IS NULL` as an attempt to consider this, but I'm not sure if that's the best way to go about it. Let me know if there's something better 👍
=> chore: add abandonment rate admin query

apps/alert_processor/lib/model/query.ex
Example output:
These columns match what was requested in the ticket, though maybe we can drop the `start` column and just have `new` and `end`? 🤔
=> chore: add retention rate query

apps/alert_processor/lib/dissemination/sms_opt_out_worker.ex
Let me know if there are any concerns here around using `Process.sleep` that I'm not aware of :)
=> fix: manually rate limit fetching opted out list in opt out worker

apps/alert_processor/lib/dissemination/sms_opt_out_worker.ex
Running into some throttling according to Splunk, so this PR adds some rate limiting via sleep
=> Add rate limit to `SMSOptOutWorker`

apps/alert_processor/lib/rules_engine/subscription_filter_engine.ex
Let me know if I've missed anything or you'd like any additional information logged here
=> feat: add some extra logging to further diagnose performance issues

.tool-versions, Dockerfile, apps/concierge_site/assets/package-lock.json, apps/concierge_site/assets/package.json
No ticket, the previous Erlang version wasn't building successfully on my machine
Also ran: `npx browserslist@latest --update-db`.
=> build: Update Erlang to the latest 24.x version 24.3.4.5

apps/alert_processor/lib/api/api_client.ex, apps/concierge_site/assets/package-lock.json
No ticket.
Unrelated, but snuck it in just because it bugged me while testing:
- feat: Change "successfully parsed" logs to debug level
=> deps: Update minor/patch versions of npm packages

.tool-versions, Dockerfile
- elixir: 1.14.2-otp-25 -> 1.14.3-otp-25
- erlang: 25.1.2 -> 25.2.2
- nodejs: 18.12.1 -> 18.14.0
=> deps: Update language versions

apps/alert_processor/test/alert_processor/model/subscription_test.exs, apps/alert_processor/test/alert_processor/service_info/service_info_cache_test.exs, apps/concierge_site/assets/package-lock.json
No ticket. Recent GTFS changes broke a couple of tests.
=> fix (test): Adjust test expectations to match latest GTFS data

apps/concierge_site/assets/package-lock.json
- bump core-js from 3.27.2 to 3.28.0 in /apps/concierge_site/assets #1287
- build(deps-dev): bump sass from 1.58.0 to 1.58.3 in /apps/concierge_site/assets #1290
- build(deps-dev): bump @babel/core from 7.20.12 to 7.21.0 in /apps/concierge_site/assets #1293
=> build(deps): Update 3 npm dependencies

apps/alert_processor/test/integration/matching_test.exs
No Asana ticket, fixes tests that are currently breaking in `main`.
=> fix (test): Update test data to match current schedule

apps/concierge_site/assets/js/radio-toggle.js, apps/concierge_site/lib/templates/account/edit_keycloak.html.eex
Updates to the Account Settings page to group notification and account settings separately
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204441906918191
=> Update account settings page

apps/alert_processor/lib/model/query.ex
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204392487059360
- https://app.asana.com/0/0/1204392487059364
=> Time Window and Fully Paused Account Queries

apps/alert_processor/test/alert_processor/service_info/service_info_cache_test.exs
No Asana ticket. I noticed this test was failing.
=> fix (test): Updated ferry stop data

apps/alert_processor/test/alert_processor/service_info/service_info_cache_test.exs
No Asana task, I just noticed this test started failing with the new GTFS data.
=> fix (test): Include test expectations for the Winthrop Ferry

apps/alert_processor/lib/model/query.ex
Now excludes users with communication mode of 'none'
asana task: https://app.asana.com/0/0/1205062662253853/f
=> Update to parallel bus routes query

apps/alert_processor/lib/model/query.ex
Asana task: https://app.asana.com/0/1167196461144361/1204898712337424/f
=> adds multiple trips query

apps/concierge_site/assets/js/bus-direction-toggle.js, apps/concierge_site/assets/js/select-multi-fix.js
This fixes multiselect for bus routes.
Asana task: https://app.asana.com/0/1167196461144361/1204555435547661/f
=> Update alternate route field id

apps/alert_processor/test/alert_processor/service_info/service_info_cache_test.exs, apps/concierge_site/lib/templates/account/edit.html.eex, apps/concierge_site/lib/templates/layout/_delete_modal.html.eex, apps/concierge_site/lib/templates/layout/app.html.eex
Asana ticket: https://app.asana.com/0/1167196461144361/1205257335187891/f
"Delete my account" link is reworded to "Delete my subscriptions"
Confirmation modal is reworded to "Are you sure you want to delete all your subscriptions?"
"Sign in" link is removed from deletion confirmation screen
=> Small changes to delete flow

apps/alert_processor/lib/model/query.ex
I was looking at this in prod and realized it would be much nicer to look at if it were sorted. No ticket.
=> Add sorting to active users query

apps/alert_processor/test/alert_processor/service_info/service_info_cache_test.exs
No Asana ticket, fixes tests that are currently breaking.
Aligns the test with the current schedules.
=> fix (test): Remove Georges Island boat from the expected results

apps/alert_processor/test/alert_processor/service_info/service_info_cache_test.exs
No ticket. Addresses a test that just started failing.
=> fix (test): Remove Lynn Ferry to match current GTFS data

apps/alert_processor/test/alert_processor/service_info/service_info_cache_test.exs
No Asana ticket. This address a [failing test](https://github.com/mbta/alerts_concierge/actions/runs/7065019923/job/19234211335).
=> fix (test): Update data to leave the Lynn Ferry but remove the stops

CONTRIBUTORS.md
Asana ticket: [Add a CONTRIBUTORS.md file to alerts-concierge](https://app.asana.com/0/1167196461144361/1205837253862463)
We want to recognize the entire team, not just the engineers.
=> docs: List all of the contributors to this project

apps/alert_processor/lib/dissemination/notification_sender.ex, apps/alert_processor/test/alert_processor/dissemination/notification_sender_test.exs, apps/concierge_site/assets/mjml/notification.mjml, apps/concierge_site/lib/mail_templates/notification.txt.eex
Asana ticket: https://app.asana.com/0/1167196461144361/1206292714715118/f
- Adds notification urls to sms and plain text emails
- removes margin: 0 from emails
=> Add urls to notifications

Dockerfile, apps/alert_processor/lib/repo.ex, apps/alert_processor/test/alert_processor/service_info/service_info_cache_test.exs, apps/concierge_site/test/web/views/route_select_helper_test.exs, config/runtime.exs
Asana ticket: https://app.asana.com/0/1167196461144361/1206249244818761/f
This deployed correctly!
=> Configure Database to use SSL

Dockerfile, apps/alert_processor/lib/repo.ex, config/runtime.exs
This puts main back to the way it was before any of the two SSL commits.
=> Revert to previous state

Dockerfile, config/runtime.exs
Asana ticket: https://app.asana.com/0/1167196461144361/1206249244818761/f
Deployed to dev-green AND no errors in Splunk.
=> SSL configuration

apps/concierge_site/lib/controllers/unsubscribe_controller.ex, apps/concierge_site/lib/router.ex, apps/concierge_site/test/web/controllers/unsubcribe_controller_test.exs
Asana ticket: https://app.asana.com/0/1167196461144361/1206700151817926/f
=> add unsubscribe route

apps/concierge_site/config/config.exs, apps/concierge_site/config/test.exs, apps/concierge_site/lib/dissemination/email.ex, apps/concierge_site/lib/dissemination/notification_email.ex, apps/concierge_site/test/lib/dissemination/email_test.exs, apps/concierge_site/test/lib/dissemination/notification_email_test.exs, apps/concierge_site/test/web/controllers/unsubcribe_controller_test.exs, config/runtime.exs
Asana ticket: https://app.asana.com/0/1167196461144361/1206571160766103/f
=> Adds unsubscribe email header

apps/alert_processor/test/alert_processor/service_info/service_info_cache_test.exs
No Asana ticket. Fixes a test case that is currently broken.
=> fix (test): Latest ferry schedules

apps/concierge_site/config/config.exs, apps/concierge_site/config/test.exs, apps/concierge_site/lib/controllers/unsubscribe_controller.ex, apps/concierge_site/lib/dissemination/email.ex, apps/concierge_site/lib/dissemination/notification_email.ex, apps/concierge_site/lib/router.ex, apps/concierge_site/test/lib/dissemination/email_test.exs, apps/concierge_site/test/lib/dissemination/notification_email_test.exs, apps/concierge_site/test/web/controllers/unsubcribe_controller_test.exs, config/runtime.exs
Asana ticket: https://app.asana.com/0/1167196461144361/1206571160766103/f
This is to merge the feature branch into main. The code has already been reviewed separately.
=> Unsubscribe Feature branch merge

apps/concierge_site/assets/package-lock.json
Fixes a broken CI run in main.
=> fix (deps): Bump phoenix_html from 3.3.1 to 3.3.3

apps/alert_processor/test/alert_processor/service_info/service_info_cache_test.exs
No Asana ticket; tests were failing.
=> fix (test): Update expected Long Wharf stop details

apps/alert_processor/test/alert_processor/service_info/service_info_cache_test.exs
No Asana ticket; tests were failing.
=> fix (test): New name of Winthrop Ferry

apps/alert_processor/lib/user_update_worker.ex, apps/alert_processor/test/alert_processor/user_update_worker_test.exs, apps/concierge_site/lib/controllers/auth_controller.ex, apps/concierge_site/test/web/controllers/auth_controller_test.exs
[Asana Ticket](https://app.asana.com/0/1204819229687089/1207720143191506/f)
Updates the user update worker so it works whether the user has an id or mbta_uuid field.
Updates auth_controller to not throw error if mbta_uuid is missing.
=> updates user_update_worker to take either id or mbta_uuid as user id

Dockerfile
No ticket, it's failing here too, let's just get rid of it.
=> Remove the checksum in Concierge too

apps/alert_processor/test/alert_processor/api/api_client_test.exs, apps/alert_processor/test/alert_processor/service_info/service_info_cache_test.exs, apps/alert_processor/test/integration/matching_test.exs, apps/concierge_site/lib/controllers/auth_controller.ex, apps/concierge_site/lib/ueberauth/strategy/fake_keycloak.ex, config/config.exs, config/dev.exs
- Fixes fake Keycloak strategy
- updates tests for new rating
=> Fixes fake keycloak strategy & updates tests for new riding

config/prod.exs
#1457 broke the Docker container build; this fixes it.
=> fix: create empty root config for prod

apps/concierge_site/lib/controllers/admin/scr_controller.ex
If this isn't sufficient, then we might be able to partition out the subscription UUIDs by leading digit and migrate 1/16 of them at a time, but I hope we don't need to do that. If this app already had Oban set up I'd be just running this as an Oban job instead, but setting that up just for this feels like more trouble than it's worth.
=> fix: raise timeout on some big SCR migration queries

apps/concierge_site/lib/controllers/admin/scr_controller.ex, apps/concierge_site/test/web/controllers/admin/scr_controller_test.exs
Since these take too long to load, and the risk created by not copying them is not severe, this seems like the best approach.
=> fix: skip notification_subscriptions in SCR migration
